# 010. PyTorch basic

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cuda:0'

In [2]:
torch.__version__

'2.0.1+cu118'

## Tensor Data Types

<img src="https://miro.medium.com/max/875/1*-C10tKbZ2h0Zd7maau86oQ.png" height="400" />

### torch.tensor 함수

`tensor(data, dtype=None, device=None, requires_grad=False) -> Tensor`

     data (array_like): list, tuple, numpy ndarray, scalar, and other types.
     dtype :  `None`인 경우 `data`에서 데이터 유형을 유추합니다.  
     device : `cpu`, `cuda`  
     require_grad(bool, optional): autograd가 작업을 기록해야 하는 경우

Float torch tensor 생성

In [3]:
# numpy array 생성
a = np.ones((2, 3))
# tensor  생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float64 	 torch.float64


In [4]:
# numpy 생성
a = np.ones((2, 3), dtype="float32")
# tensor 생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float32 	 torch.float32


Integer tensor 생성

In [5]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
x

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [6]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32, device=device)
x

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0', dtype=torch.int32)

## 1D Tensor Operation

### tensor 생성

In [7]:
a = torch.tensor([1, 2, 3, 4, 5])

a[0], a[-1]

(tensor(1), tensor(5))

In [8]:
a.size()

torch.Size([5])

In [9]:
a.ndimension()

1

In [10]:
a.view(5, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [11]:
# cpu tensor
a = torch.FloatTensor([0, 1, 2, 3, 4])
a

tensor([0., 1., 2., 3., 4.])

In [12]:
# gpu tensor
a = torch.cuda.FloatTensor([0, 1, 2, 3, 4])
a

tensor([0., 1., 2., 3., 4.], device='cuda:0')

### Tensor Type 변환

- cpu <--> gpu

In [13]:
# cpu tensor
a = a.type(torch.FloatTensor)
a

tensor([0., 1., 2., 3., 4.])

In [14]:
# gpu tensor
b = a.to(device)
b

tensor([0., 1., 2., 3., 4.], device='cuda:0')

In [15]:
b = a.cuda()
b

tensor([0., 1., 2., 3., 4.], device='cuda:0')

In [16]:
c = a.type(torch.cuda.FloatTensor)
c

tensor([0., 1., 2., 3., 4.], device='cuda:0')

In [17]:
# cpu tensor
d = b.to("cpu")
d

tensor([0., 1., 2., 3., 4.])

In [18]:
e = c.cpu()
e

tensor([0., 1., 2., 3., 4.])

### Tensor 생성

- 무작위로 초기화된 행렬 생성 (uniform distribution)

In [31]:
x = torch.rand(5, 3) 
print(x)
print(x.dtype)

tensor([[0.3130, 0.0149, 0.0053],
        [0.8379, 0.6235, 0.2854],
        [0.8923, 0.2663, 0.6834],
        [0.8489, 0.4078, 0.6265],
        [0.9464, 0.6870, 0.3076]])
torch.float32


- dtype이 long이고 0으로 채워진 행렬 생성

In [30]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


- python list로 부터 tensor 생성

In [32]:
a = torch.tensor([7, 4, 3, 2, 6])
a.type(), a.dtype

('torch.LongTensor', torch.int64)

In [33]:
b = torch.FloatTensor([7, 4, 3, 2, 6])
b.type(), b.dtype

('torch.FloatTensor', torch.float32)

In [34]:
a == b

tensor([True, True, True, True, True])

## Tensor 의 shape & dimension (rank)

In [36]:
a = torch.Tensor([0, 1, 2, 3, 4])
a.size()

torch.Size([5])

In [37]:
# size() 와 shape 은 alias
a.shape

torch.Size([5])

In [38]:
a.ndimension()

1

## reshape
- torch.view : original tensor의 memory 공유 (contiguity 제한)
- torch.reshape: contiguity 제한 없음. 필요에 따라 new tensor 생성. numpy 와 유사한 operation을 위해 기능 제공

In [39]:
print(a)
print(a.view(5, 1))
print(a.reshape(5, 1))

tensor([0., 1., 2., 3., 4.])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])


In [40]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)        

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [41]:
x = torch.randn(4, 4)
y = x.reshape(16)
z = x.reshape(-1, 8)         

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [42]:
x = torch.randn(4, 4)
x

tensor([[-0.4406, -1.3764,  1.4053, -0.5151],
        [-1.5786, -0.2970, -0.6030, -0.2987],
        [-1.2694, -0.7228,  1.3517, -0.2331],
        [ 1.2605, -0.0420,  0.3699,  1.3131]])

In [43]:
x.is_contiguous()

True

In [44]:
# dim0, dim1 을 swap
x.transpose(0, 1)

tensor([[-0.4406, -1.5786, -1.2694,  1.2605],
        [-1.3764, -0.2970, -0.7228, -0.0420],
        [ 1.4053, -0.6030,  1.3517,  0.3699],
        [-0.5151, -0.2987, -0.2331,  1.3131]])

In [45]:
x.transpose(0, 1).is_contiguous()

False

In [46]:
x.transpose(0, 1).reshape(-1, 8)

tensor([[-0.4406, -1.5786, -1.2694,  1.2605, -1.3764, -0.2970, -0.7228, -0.0420],
        [ 1.4053, -0.6030,  1.3517,  0.3699, -0.5151, -0.2987, -0.2331,  1.3131]])

In [47]:
x.transpose(0, 1).view(-1, 8)

RuntimeError: ignored

## numpy 와 tensor 간의 호환성

- memory 를 공유하므로 하나를 수정하면 나머지에 모두 반영  

In [48]:
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])       # numpy array
torch_tensor = torch.from_numpy(numpy_array)               # torch tensor
torch_tensor 

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [49]:
back_to_numpy = torch_tensor.numpy()           # numpy array
back_to_numpy

array([0., 1., 2., 3., 4., 5.])

In [50]:
numpy_array, torch_tensor, back_to_numpy

(array([0., 1., 2., 3., 4., 5.]),
 tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64),
 array([0., 1., 2., 3., 4., 5.]))

In [51]:
back_to_numpy[0] = 100

numpy_array, torch_tensor, back_to_numpy

(array([100.,   1.,   2.,   3.,   4.,   5.]),
 tensor([100.,   1.,   2.,   3.,   4.,   5.], dtype=torch.float64),
 array([100.,   1.,   2.,   3.,   4.,   5.]))

## Scalar value 

- 만약 tensor에 하나의 값만 존재한다면, ``.item()`` method를 사용하여 scalar 숫자 값을 얻을 수 있습니다.  

In [52]:
x = torch.randn(1)
x.item()

1.5810456275939941

In [53]:
a = torch.tensor([5., 3., 4., 1.])

print(a[0])
print(a[0].item())

tensor(5.)
5.0


- tensor 가 array 형태인 경우 `numpy()` method 를 통해 ndarray 반환

In [54]:
x = torch.randn(2)
print(x)
print()
print(x.numpy())

tensor([-1.3723,  1.4456])

[-1.3723226  1.4455768]


## Tensor 의 indexing & slicing

- Python 의 indexing & slicing 과 동일

In [55]:
c = torch.tensor([20, 1, 2, 3, 4])
c[0] = 100
c[4] = 0
c, c.dtype

(tensor([100,   1,   2,   3,   0]), torch.int64)

In [56]:
d = c[1:4]
d

tensor([1, 2, 3])

In [57]:
c[3:5] = torch.tensor([300.0, 400.0])
c

tensor([100,   1,   2, 300, 400])

## Basic Operations - numpy 와 동일

In [58]:
# element-wise 덧셈, 뺄셈 
u = torch.tensor([1.0, 0.0])
v = torch.tensor([0.0, 1.0])
z = u + v
z

tensor([1., 1.])

In [59]:
z = u - v
z

tensor([ 1., -1.])

In [60]:
# element-wise 곱셈
u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
z = u * v
z

tensor([3, 4])

In [61]:
# 스칼라 곱
y = torch.tensor([1, 2])
z = 2 * y
z

tensor([2, 4])

## 기타

In [62]:
# broadcasting
u = torch.tensor([1, 2, 3, -1])
z = u + 1          
z

tensor([2, 3, 4, 0])

In [63]:
# mean, max, Standard Deviation
a = torch.tensor([1, -2, 3, 4, 5], dtype=torch.float32)

a.mean(), a.max(), a.std()

(tensor(2.2000), tensor(5.), tensor(2.7749))

## 2D Tensor Operation

In [64]:
_2d_tensor = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
_2d_tensor

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33],
        [41, 42, 43]])

- ndimension  
- shape  
- size()  
- numel (number of elements)

In [65]:
print(_2d_tensor)
print(_2d_tensor.ndimension())
print(_2d_tensor.shape)
print(_2d_tensor.size())
print(_2d_tensor.numel())

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33],
        [41, 42, 43]])
2
torch.Size([4, 3])
torch.Size([4, 3])
12


### Concatenation

- default - first axis(row-wise)로 concatenate
- column-wise로 concatenate 하려면 axis=1 로 지정

In [66]:
x_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_2 = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(x_1)
print(x_2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [67]:
torch.cat([x_1, x_2])

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [68]:
torch.cat([x_1, x_2], axis=1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

### torch.sum, torch.max, torch.min, torch.argmax, torch.argmin

- torch.sum(input, dim, keepdim=False, dtype=None) → Tensor  
주어진 차원 dim에서 입력 텐서의 각 행의 합(max, min)을 반환합니다.

- dim 을 지정한 경우, 지정된 dim을 축소하는 것입니다. 따라서 dim 0(행)을 접으면 하나의 행이 됩니다(열 단위로 합산).

In [69]:
x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])
x.shape

torch.Size([2, 3])

In [70]:
torch.sum(x)

tensor(21)

In [71]:
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [72]:
torch.sum(x, dim=1)

tensor([ 6, 15])

In [74]:
value, idx = torch.max(x, axis=0)
value, idx

(tensor([4, 5, 6]), tensor([1, 1, 1]))

In [76]:
value, idx = torch.min(x, axis=0)
value, idx

(tensor([1, 2, 3]), tensor([0, 0, 0]))

In [77]:
value, idx = torch.max(x, axis=1)
value, idx

(tensor([3, 6]), tensor([2, 2]))

In [78]:
value, idx = torch.min(x, axis=1)
value, idx

(tensor([1, 4]), tensor([0, 0]))

In [79]:
torch.argmax(x), torch.argmin(x)

(tensor(5), tensor(0))

In [80]:
torch.argmax(x, axis=0), torch.argmin(x, axis=0)

(tensor([1, 1, 1]), tensor([0, 0, 0]))

In [81]:
torch.argmax(x, axis=1), torch.argmin(x, axis=1)

(tensor([2, 2]), tensor([0, 0]))